### ISSUE TITLE
Would implementing style_transfer's tiling solution in Neural-Style be possible?

### ISSUE THREAD

**Issue by ProGamerGov** [crowsonkb/style_transfer#10]
I can see the tiling code for style_transfer [here](https://github.com/crowsonkb/style_transfer/blob/master/style_transfer.py#L539-L559).

I have been trying to implement tiling into Neural-Style with a [tiling script](https://github.com/ProGamerGov/Neural-Tile), but I can't seem to solve the problem of "style shift" that occurs between the tiles. I know style_transfer seems to solve this problem, but is style_transfer's solution able to be implemented in LUA or Bash/Shell? Or should I seek a different solution?

**Edit:** To clarify, I am asking whether or not your tiling solution requires things that are not available in Lua, and whether or it requires a compiled version of Caffe.

**Comment by crowsonkb** [comment]
It should be implementable in Lua but I think it would not be possible to do as an external script. It works by splitting the image into differently offset tiles each iteration, recombining the processed tiles, and applying tile seam suppression. This stops visible tile seams from accumulating in the image. Also, you have to compute the target feature maps and Gram matrices in a tiled way so that you do not run out of memory.
